name: Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Instalar dependências e Build
        run: |
          npm install
          npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/

          # O local correto na Hostinger
          server-dir: ./public_html/

          # A SOLUÇÃO MÁGICA:
          # Mudamos o nome do arquivo de controle. O robô vai achar que é a
          # primeira vez e não vai tentar deletar a pasta '_next' antiga que dava erro 550.
          state-name: .ftp-deploy-sync-state-v2.json

          dangerous-clean-slate: false
